# Generated by Django 4.0.8 on 2023-05-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_portal', models.CharField(blank=True, choices=[('linkedin', 'Linkedin'), ('vietnamworks', 'Vietnamworks'), ('topcv', 'TopCV')], max_length=50, null=True)),
                ('job_title', models.CharField(blank=True, max_length=511, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
