# Generated by Django 4.0.8 on 2023-05-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='searching_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
