# Generated by Django 4.0.8 on 2022-12-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_template', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumetemplate',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='category',
            field=models.CharField(choices=[('Creative', 'Creative'), ('Simple', 'Simple'), ('Professional', 'Professional'), ('Modern', 'Modern')], default='Creative', max_length=50),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
