# Generated by Django 4.0.8 on 2022-12-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_template', '0002_rename_name_resumetemplate_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetemplate',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
