# Generated by Django 4.0.8 on 2022-10-16 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
        ('resume_form', '0002_complexsection_personaldetails_resume_workexperience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexsection',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.resume'),
        ),
    ]
