# Generated by Django 4.0.8 on 2022-10-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_form', '0003_alter_complexsection_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
