# Generated by Django 4.0.8 on 2022-10-18 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
        ('resume_form', '0004_alter_personaldetails_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexsection',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complex_sections', to='resume.resume'),
        ),
        migrations.AlterField(
            model_name='custom',
            name='complex_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_items', to='resume_form.complexsection'),
        ),
        migrations.AlterField(
            model_name='education',
            name='complex_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='resume_form.complexsection'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='complex_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employment_histories', to='resume_form.complexsection'),
        ),
        migrations.AlterField(
            model_name='link',
            name='complex_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='resume_form.complexsection'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='complex_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume_form.complexsection'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='complex_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='resume_form.complexsection'),
        ),
    ]
