# Generated by Django 4.0.8 on 2022-10-20 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_form', '0005_alter_complexsection_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complexsection',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custom',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='professionalsummary',
            name='position',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='skill',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custom',
            name='complex_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customs', to='resume_form.complexsection'),
        ),
    ]
