# Generated by Django 4.0.8 on 2022-10-21 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_resume_template_alter_resume_user'),
        ('resume_form', '0006_complexsection_position_custom_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='resume',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to='resume.resume'),
        ),
        migrations.AlterField(
            model_name='professionalsummary',
            name='resume',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professional_summary', to='resume.resume'),
        ),
    ]
