# Generated by Django 4.0.8 on 2022-12-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_form', '0007_alter_personaldetails_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(blank=True, choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('skillful', 'Skillful'), ('experienced', 'Experienced'), ('master', 'Master')], default='beginner', max_length=20),
        ),
    ]
