# Generated by Django 4.0.8 on 2023-01-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_form', '0008_alter_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(blank=True, choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('skillful', 'Skillful'), ('experienced', 'Experienced'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
    ]
