# Generated by Django 4.0.8 on 2023-02-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_form', '0010_complexsection_section_type_delete_workexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
