# Generated by Django 4.0.8 on 2023-05-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_form', '0011_alter_personaldetails_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexsection',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='custom',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
