# Generated by Django 4.0.8 on 2023-03-31 09:41

from django.db import migrations, models
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resume_created_at_resume_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=resume.models.image_upload_to),
        ),
        migrations.AddField(
            model_name='resume',
            name='thumbnail',
            field=models.TextField(null=True, blank=True)
        ),
    ]
