# Generated by Django 4.0.8 on 2023-04-01 13:35

from django.db import migrations, models
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_resume_image_resume_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=resume.models.thumbnail_upload_to),
        ),
    ]
