# Generated by Django 4.0.8 on 2023-04-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_resume_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='layout',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
