# Generated by Django 4.0.8 on 2023-05-12 04:50

from django.db import migrations, models
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_resume_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default_images/resume_thumbnails/new_resume_thumbnail.png', null=True, upload_to=resume.models.thumbnail_upload_to),
        ),
    ]
